/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Content {
  'features' : Array<string>,
  'instagramLink' : string,
  'pressEmail' : string,
  'bodyTextColorHex' : string,
  'developerWebsite' : string,
  'gameDetails' : GameDetails,
  'aboutText' : string,
  'passwordEnabled' : boolean,
}
export interface GameDetails {
  'genre' : string,
  'platforms' : string,
  'releaseDate' : string,
}
export interface UserProfile { 'principal' : Principal, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCallerUserProfile' : ActorMethod<[], undefined>,
  'disablePasswordProtection' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'enablePasswordProtection' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContent' : ActorMethod<[], Content>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAdmin' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAbout' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'updateBodyTextColor' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateDeveloperWebsite' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateFeatures' : ActorMethod<
    [Array<string>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateGameDetails' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateInstagram' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updatePressEmail' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'verifyAdmin' : ActorMethod<[], { 'ok' : boolean } | { 'err' : string }>,
  'verifyPassword' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];